### ISSUE TITLE
Missing pegen header file

### ISSUE THREAD

**Issue by smichaut** [we-like-parsers/pegen#249]
Hi,
I have tried to compile the project on Redhat after installing Python 3.10.0a1, running make in the root directory and I have the following error :
.../pegen-master/peg_extension/peg_extension.c:1:10: fatal error: pegen.h: No such file or directory
 #include "pegen.h"

This prevents me to test the new PEG parser!!!

**Comment by lysnikolaou** [comment]
That's probably because you need to have an env variable set, that holds the path to a clone of the CPython repo. You can run something like: `CPYTHON_ROOT="/home/user/repos/cpython" make` and it'll solve this problem. Unfortunately, there are some more compatibility issues with 3.10, that currently make it impossible to compile pegen. I'll try and push a PR later today to fix those.
