### ISSUE TITLE
Avoid accidental clashes between names in grammar and infrastructure

### ISSUE THREAD

**Issue by gvanrossum** [we-like-parsers/pegen#84]
Items in an alternative may be named, and the names may be referenced in actions. But there are some "forbidden" names. E.g. don't name an item `p`, because (when generating C code) every rule parsing function has an argument named `p`. There are other possible name clashes too: `res` and `mark` are always local variables. And there are many helper functions, with names like `is_memoized` or `singleton_seq`. And of course anything that's a C reserved word (e.g. `if`) cannot be used either. Also there are systematic generated names like `*_var`, `*_type` and `*_rule`.

It's easy to rename `p`, `mark` and `res` in the generated code to start with an underscore (by convention, rule names don't start with `_`, and maybe we should make this a hard requirement). I'm not sure we need to worry about the others, though we may have to warn about them in the docs.

When generating Python code there are other possible clashes, e.g. `self`, `mark` and `cut`. We can handle these the same way. (There are a few others that seem less important, like `ast` and of course Python builtins and keywords.)

**Comment by apalala** [comment]
The same problem is still present in TatSu, because generated AST nodes descend from a base `Node` class, and collisions may happen with Python keywords, and with methods and attributes defined  in `Node`. I want to do something drastic there, because collisions continue to appear, but there is backwards compatibility to care about.

In the case of `pgen`, readability of the grammar and the supporting C library code should be more important than that of the generated parser, so I favor altering the identifiers generated for the names in the grammar to something unlike the standards for CPython C code, like:

* `_r_arulename` for rules
* `__f_aname` for parts named on RHSides

A regex substitution can take care of renaming the names mentioned in semantic actions.

Consider that the currently generated LL(1) parser is mostly unreadable.

**Comment by gvanrossum** [comment]
Moved to https://github.com/we-like-parsers/cpython/issues/125.
